import  ReactDOM  from "react-dom/client";
// import Sum from "./sum";
// import Intro from "./intro";
// import Five from "./five";
// import Six from "./six";
// import Cards from "./assign1";
// import Eight from "./Eight";
// import Assign2 from "./assign2";
// import Nine from "./Nine";
// import Login from "./login";
// import Twelve from "./Twelve";
// import Eleven from "./Eleven";
import App from "./App";
// import Assign3 from "./assign3";
import Thirteen from "./Thirteen";
const rootElement = document.getElementById('root');
const rootRef = ReactDOM.createRoot(rootElement);
// let a= 23;
// let b=26;
// let res= Sum(a,b);
rootRef.render(<App/>);
// rootRef.render(res);
